# OVAV Fish Aliases — Cross-terminal unified shortcuts
# Source: .ovav/source/configs/commands/aliases.fish
# Generated by: ovav convert
# =============================================================================

# Navigation shortcuts
alias home "cd ~"
alias sys "cd ~/.config"

# ovav — smart dispatch: no args = cd, with args = forward to binary
# FIX: alias ovav "cd ~/Systems/OVAV" broke "ovav login" → fish expanded to
# "cd ~/Systems/OVAV login" → "Too many args for cd command".
# Root fix: function instead of alias — detects argument presence and routes
# to the correct handler (cd or binary) automatically.
function ovav
    if test (count $argv) -eq 0
        cd ~/Systems/OVAV
    else
        command ovav $argv
    end
end

# Workspace shortcuts
alias wh "cd ~/"
alias ws "cd ~/.config"
alias wo "cd ~/Systems/OVAV"

# Git shortcuts
alias gs "git status"
alias ga "git add"
alias gc "git commit"
alias gp "git push"
alias gl "git log --oneline"
alias gd "git diff"
alias gco "git checkout"
alias gb "git branch"
alias gm "git merge"
alias gr "git rebase"

# OVAV commands
alias ov "ovav"
alias ovs "ovav status"
alias ovc "ovav convert"
alias ovv "ovav validate"
alias ovd "ovav doctor"

# Worktree shortcuts
alias owc "git worktree add"
alias owl "git worktree list"
alias owv "git worktree remove"

# Utility shortcuts
alias ll "ls -la"
alias la "ls -a"
alias l "ls -la"
alias c "clear"
alias k "kubectl"
alias d "docker"

# Development shortcuts
alias py "python3"
alias pi "pip install"
alias pg "psql"
alias rg "rg"

# Fish-specific
alias reload "source ~/.config/fish/config.fish"
