# OVAV Bash Aliases — Cross-terminal unified shortcuts
# Source: .ovav/source/configs/commands/aliases.sh
# Generated by: ovav convert
# =============================================================================

# Navigation shortcuts
alias home="cd ~"
alias sys="cd ~/.config"
alias ovav="cd ~/Systems/OVAV"

# Workspace shortcuts
alias wh="cd ~/"
alias ws="cd ~/.config"
alias wo="cd ~/Systems/OVAV"

# Git shortcuts
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gl="git log --oneline"
alias gd="git diff"
alias gco="git checkout"
alias gb="git branch"
alias gm="git merge"
alias gr="git rebase"

# OVAV commands
alias ov="ovav"
alias ovs="ovav status"
alias ovc="ovav convert"
alias ovv="ovav validate"
alias ovd="ovav doctor"

# Worktree shortcuts
alias owc="git worktree add"
alias owl="git worktree list"
alias owv="git worktree remove"

# Utility shortcuts
alias ll="ls -la"
alias la="ls -a"
alias c="clear"
