/**
 * OVAV Status Plugin — OpenCode Server Plugin v3.0
 *
 * Monitors OVAV governance state and surfaces it via:
 *   - ovav_status tool — full system status query
 *   - Toast notifications — critical state changes (budget, degradation)
 *   - Event hooks — session-level monitoring
 *
 * Reads from .ovav/runtime/ovav_status.json (generated by Python engine).
 * Uses the SERVER plugin pattern (PluginInput → Hooks), NOT TUI slots.
 *
 * v3.0: Rewritten as server plugin. TUI slot API is internal-only;
 *       external plugins use PluginInput + client.tui API.
 */

import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

// ── State reader ──────────────────────────────────────────────────────────────

function readOvavState(directory) {
  if (!directory) return null;
  const path = join(directory, ".ovav", "runtime", "ovav_status.json");
  if (!existsSync(path)) return null;
  try {
    const data = JSON.parse(readFileSync(path, "utf8"));
    return data.ovav || null;
  } catch {
    return null;
  }
}

// ── Plugin ────────────────────────────────────────────────────────────────────

export const OvavStatus = async ({ client, directory }) => {
  // Silent startup — tools available on demand via ovav_status / ovav_health

  // ── State ──
  let ovavState = null;
  let lastOverall = null;
  let pollInterval = null;

  const refresh = () => {
    const s = readOvavState(directory);
    if (s) ovavState = s;
    return ovavState;
  };

  // ── Toast helpers ──
  const toast = (message, variant = "info", duration = 4000) => {
    try {
      if (client?.tui?.toast?.show) {
        client.tui.toast.show({ message, variant, duration });
      } else {
        console.log("[OVAV Status]", message);
      }
    } catch (e) {
      console.log("[OVAV Status] Toast unavailable:", e.message);
    }
  };

  // ── Lazy init: first refresh deferred to first tool call ──
  // No I/O at plugin load — eliminates startup latency.
  let initialized = false;

  const lazyRefresh = () => {
    if (!initialized) {
      refresh();
      initialized = true;
      // Start polling after first access (lightweight, 60s interval)
      pollInterval = setInterval(() => {
        const prev = lastOverall;
        refresh();
        const current = ovavState?.overall;
        lastOverall = current;
      }, 60000); // Every 60s (was 15s)
    }
    refresh();
    return ovavState;
  };

  // ── Session monitoring ──
  let sessionStart = null;

  return {
    dispose: () => {
      if (pollInterval) clearInterval(pollInterval);
      // Silent dispose — cleanup complete
    },

    event: async ({ event }) => {
      switch (event.type) {
        case "session.created": {
          sessionStart = Date.now();
          // Deferred refresh — no I/O during init
          break;
        }

        case "session.idle": {
          sessionStart = null;
          break;
        }

        case "session.status": {
          // Refresh only if already initialized
          if (initialized) refresh();
          break;
        }

        case "tool.execute.after": {
          // Refresh only if already initialized
          if (initialized) refresh();
          break;
        }
      }
    },

    tool: {
      ovav_status: {
        description:
          "Get OVAV system status — governor, memory, integrity, branch, capsule, tokens, metrics",
        parameters: {
          type: "object",
          properties: {
            section: {
              type: "string",
              description:
                "Specific section to query: governor, memory, integrity, branch, capsule, tokens, or all (default)",
              enum: ["governor", "memory", "integrity", "branch", "capsule", "tokens", "all"],
            },
          },
        },
        execute: async (args) => {
          lazyRefresh();
          const s = ovavState;
          if (!s) {
            return JSON.stringify({
              error: "OVAV state not available — run: ovav status --write-markers",
              hint: "The Go-native status engine generates marker files on demand.",
            }, null, 2);
          }

          const section = args?.section || "all";

          if (section === "all") {
            return JSON.stringify({
              overall: s.overall,
              governor: s.governor,
              memory: s.memory,
              integrity: s.integrity,
              branch: s.branch,
              capsule: s.capsule,
              tokens: s.tokens,
              session_uptime_min: sessionStart
                ? Math.round((Date.now() - sessionStart) / 60000)
                : null,
            }, null, 2);
          }

          const result = { section };
          result[section] = s[section] || null;
          return JSON.stringify(result, null, 2);
        },
      },

      ovav_health: {
        description: "Quick OVAV health check — returns OK/DEGRADED/DOWN with details",
        execute: async () => {
          lazyRefresh();
          const s = ovavState;
          if (!s) {
            return JSON.stringify({ status: "UNKNOWN", reason: "No state data" });
          }

          const issues = [];
          if (s.governor?.status !== "active") issues.push("governor_inactive");
          if (s.memory?.status !== "active") issues.push("memory_inactive");
          if (s.integrity?.status === "fail") issues.push("integrity_fail");
          if (s.capsule?.active === false) issues.push("capsule_inactive");

          return JSON.stringify({
            status: s.overall === "active" ? "OK" : s.overall === "degraded" ? "DEGRADED" : "DOWN",
            overall: s.overall,
            issues: issues.length > 0 ? issues : null,
            governor: s.governor?.status,
            memory: s.memory?.status,
            branch: s.branch?.branch,
          });
        },
      },
    },
  };
};
