/*
 * OVAV Monitor Plugin — Generated by go-runtime/internal/project/sync.go
 * DO NOT EDIT DIRECTLY. Source: .ovav/visual/monitoring/monitoring.yaml
 */

export const OVAVMonitor = async ({ client, $, project, directory }) => {
  // State
  const state = {
    currentAgent: null,
    currentModel: null,
    totalTokens: 0,
    budgetPercent: 0,
    budgetRemaining: "0",
    ovavMemoryActive: false,
    sessionActive: false,
    sessionStart: null,
    idleSince: null,
  };

  const toast = (message, duration) => {
    try { client.tui.toast.show({ message, duration }); } catch (e) {}
  };

  const checkBudget = () => {
    const percent = Math.min(100, Math.round((state.totalTokens / 1000000) * 100)) / 100;
    state.budgetPercent = Math.round(percent);
    if (percent > 90 && !state._warnedCritical) {
      state._warnedCritical = true;
      toast(`🔴 PRESUPUESTO CRÍTICO: ${state.budgetPercent}%`, 8000);
    } else if (percent > 75 && !state._warnedWarning) {
      state._warnedWarning = true;
      toast(`⚠️ Presupuesto al ${state.budgetPercent}%`, 5000);
    } else if (percent <= 75) {
      state._warnedWarning = false;
      state._warnedCritical = false;
    }
  };

  // [OVAV] Monitor plugin initialized — silent (see .ovav/logs/monitor.log)
  return {
    event: async ({ event }) => {
      switch (event.type) {
        case 'session.status': {
          const status = event.properties;
          if (!status) break;

          if (status.agent && status.agent !== state.currentAgent) {
            const prev = state.currentAgent;
            state.currentAgent = status.agent;
            if (prev) {
              toast(`🔄 ${prev} → ${state.currentAgent}`, 3000);
            }
          }

          if (status.model && status.model !== state.currentModel) {
            const prev = state.currentModel;
            state.currentModel = status.model;
            if (prev) {
              toast(`🧠 Modelo cambiado: ${prev} → ${state.currentModel}`, 3000);
            }
          }

          if (status.usage) {
            state.totalTokens = status.usage.total || status.usage.input + status.usage.output || 0;
            checkBudget();
          }
          break;
        }
        case 'session.idle':
          state.sessionActive = false;
          state.idleSince = Date.now();
          break;
        case 'session.created':
          state.sessionActive = true;
          state.sessionStart = Date.now();
          state.idleSince = null;
          break;
        case 'todo.updated':
          break;
      }
    },
    tool: {
      ovav_monitor: {
        description: 'Get OVAV monitor status',
        execute: async () => {
          const elapsed = state.sessionStart ? Math.floor((Date.now() - state.sessionStart) / 1000) : 0;
          const minutes = Math.floor(elapsed / 60);
          const seconds = elapsed % 60;
          return JSON.stringify({
            agent: state.currentAgent || 'unknown',
            model: state.currentModel || 'unknown',
            tokens: state.totalTokens,
            budgetPercent: state.budgetPercent,
            budgetRemaining: state.budgetRemaining,
            memoryActive: state.ovavMemoryActive,
            sessionElapsed: `${minutes}m ${seconds}s`,
            sessionActive: state.sessionActive,
          }, null, 2);
        },
      },
    },
  };
};
