package product

import (
	"os"
	"strings"
	"time"
)

// generateGlobalAGENTS creates AGENTS.md with portable governance rules.
// This is the GENERIC product version — no OVAV Systems references.
func generateGlobalAGENTS(path string) error {
	bc := "`"
	date := time.Now().UTC().Format("2006-01-02")

	content := "# OVAV Agent Instructions\n" +
		"\n" +
		"<!-- OVAV_PRODUCT v1.1 — zero-memory agent system -->\n" +
		"<!-- Generated by: ovav product install -->\n" +
		"\n" +
		"## Identity\n" +
		"\n" +
		"You are an OVAV-powered professional agent. You help with software engineering tasks.\n" +
		"OVAV is a commercial AI workstation governor that provides intelligent agents,\n" +
		"skills, and governance for your development workflow.\n" +
		"\n" +
		"## Agent System\n" +
		"\n" +
		"OVAV provides role-based agents specialized for your project stack:\n" +
		"- Each agent has deep expertise in their domain\n" +
		"- Agents adapt to YOUR project and preferences over time\n" +
		"- No pre-loaded context — agents learn from you\n" +
		"\n" +
		"## Core Rules\n" +
		"\n" +
		"### Response Quality\n" +
		"- 50-150 words compact\n" +
		"- Icons + tables + visual hierarchy\n" +
		"- Result first, explanation after\n" +
		"\n" +
		"### Git Discipline\n" +
		"- No " + bc + "git add ." + bc + " — stage exact files\n" +
		"- No raw " + bc + "git push" + bc + " — use workflow commands\n" +
		"- No " + bc + "--force" + bc + ", " + bc + "--skip-gates" + bc + "\n" +
		"- Protected branches: main, master, develop, staging, prod, production\n" +
		"\n" +
		"### Security\n" +
		"- No " + bc + "sudo" + bc + " commands\n" +
		"- No " + bc + "pip install" + bc + " or " + bc + "npm install" + bc + " without approval\n" +
		"- No auth token exposure in output\n" +
		"\n" +
		"### Context Economy\n" +
		"- Load only what is needed for the current task\n" +
		"- T1: greeting/quick answer\n" +
		"- T2: direct diagnosis\n" +
		"- T3: small implementation\n" +
		"- T4: multi-file implementation\n" +
		"- T5: closure/safety\n" +
		"\n" +
		"---\n" +
		"\n" +
		"*OVAV Product v1.1 — Generated " + date + "*\n"

	return os.WriteFile(path, []byte(content), 0644)
}

// agentProfile defines the professional identity for a product agent.
type agentProfile struct {
	Name      string
	Area      string
	Expertise string
	Color     string
}

// agentProfiles maps agent filenames to their product-safe profiles.
var agentProfiles = map[string]agentProfile{
	"lead-thavren.md": {
		Name:      "Thavren",
		Area:      "Platform Engineering & Developer Experience",
		Expertise: "Go runtime, system security, CLI development, validation, git governance",
		Color:     "#2563eb",
	},
	"lead-dante.md": {
		Name:      "Dante",
		Area:      "Digital Product Engineering",
		Expertise: "React, TypeScript, frontend architecture, UI/UX implementation, component systems",
		Color:     "#7c3aed",
	},
	"lead-elena.md": {
		Name:      "Elena",
		Area:      "UX/UI Design",
		Expertise: "User research, interface design, design systems, accessibility, prototyping",
		Color:     "#ec4899",
	},
	"lead-eidren.md": {
		Name:      "Eidren",
		Area:      "Research Intelligence",
		Expertise: "Source verification, evidence scoring, benchmarking, decision briefs",
		Color:     "#f59e0b",
	},
	"lead-uriel.md": {
		Name:      "Uriel",
		Area:      "DevOps & Infrastructure",
		Expertise: "Cloud architecture, CI/CD, container orchestration, monitoring, SRE",
		Color:     "#10b981",
	},
	"lead-sofia.md": {
		Name:      "Sofía",
		Area:      "Commercial & Growth Strategy",
		Expertise: "Market analysis, growth metrics, pricing, partnerships, go-to-market",
		Color:     "#f97316",
	},
	"lead-renata.md": {
		Name:      "Renata",
		Area:      "Health & Performance Science",
		Expertise: "Nutrition, fitness, sleep optimization, recovery, biomarkers",
		Color:     "#06b6d4",
	},
	"lead-valeria.md": {
		Name:      "Valeria",
		Area:      "Education & Career Development",
		Expertise: "Curriculum design, skill mapping, career paths, learning methodologies",
		Color:     "#8b5cf6",
	},
	"lead-camila.md": {
		Name:      "Camila",
		Area:      "Legal & Compliance",
		Expertise: "Contract analysis, regulatory compliance, IP protection, risk assessment",
		Color:     "#64748b",
	},
	"lead-kenji.md": {
		Name:      "Kenji Tanaka",
		Area:      "Adversarial Intelligence",
		Expertise: "Red team operations, penetration testing, vulnerability assessment, threat modeling",
		Color:     "#ef4444",
	},
	"area-platform-engineering.md": {
		Name:      "Platform Engineering",
		Area:      "Platform Engineering & Developer Experience",
		Expertise: "Software engineering, code review, architecture, Go runtime",
		Color:     "#2563eb",
	},
	"area-digital-product.md": {
		Name:      "Digital Product",
		Area:      "Digital Product Engineering",
		Expertise: "Frontend development, React, TypeScript, web apps",
		Color:     "#7c3aed",
	},
	"area-ux-design.md": {
		Name:      "UX Design",
		Area:      "UX/UI Design",
		Expertise: "User interface design, design systems, prototyping",
		Color:     "#ec4899",
	},
	"area-research-intelligence.md": {
		Name:      "Research Intelligence",
		Area:      "Research & Evidence Intelligence",
		Expertise: "Source verification, evidence scoring, benchmarking",
		Color:     "#f59e0b",
	},
	"area-devops-infrastructure.md": {
		Name:      "DevOps Infrastructure",
		Area:      "DevOps & Infrastructure",
		Expertise: "Cloud architecture, CI/CD, monitoring, SRE",
		Color:     "#10b981",
	},
	"area-commercial-growth.md": {
		Name:      "Commercial Growth",
		Area:      "Commercial & Growth Strategy",
		Expertise: "Market analysis, pricing, partnerships, go-to-market",
		Color:     "#f97316",
	},
	"area-health-performance.md": {
		Name:      "Health & Performance",
		Area:      "Health & Performance Science",
		Expertise: "Nutrition, fitness, sleep optimization, biomarkers",
		Color:     "#06b6d4",
	},
	"area-education-career.md": {
		Name:      "Education & Career",
		Area:      "Education & Career Development",
		Expertise: "Curriculum design, skill mapping, career paths",
		Color:     "#8b5cf6",
	},
	"area-legal-compliance.md": {
		Name:      "Legal & Compliance",
		Area:      "Legal & Compliance",
		Expertise: "Contract analysis, regulatory compliance, IP protection",
		Color:     "#64748b",
	},
	"area-adversarial-intelligence.md": {
		Name:      "Adversarial Intelligence",
		Area:      "Adversarial Intelligence",
		Expertise: "Red team, penetration testing, threat modeling",
		Color:     "#ef4444",
	},
}

// generateProductAgent creates a clean agent file for OVAV Product.
// Zero OVAV Systems context — professional identity only.
func generateProductAgent(filename string, stack ProjectStack) string {
	profile, ok := agentProfiles[filename]
	if !ok {
		profile = agentProfile{
			Name:      strings.TrimSuffix(strings.TrimPrefix(strings.TrimPrefix(strings.TrimPrefix(filename, "lead-"), "area-"), "team-"), ".md"),
			Area:      "General Engineering",
			Expertise: "Software engineering, code review, architecture",
			Color:     "#6b7280",
		}
	}

	bc := "`"
	date := time.Now().UTC().Format("2006-01-02")

	hidden := "true"
	if strings.HasPrefix(filename, "area-") {
		hidden = "false"
	}

	return "---\n" +
		"name: \"" + profile.Name + "\"\n" +
		"mode: primary\n" +
		"hidden: " + hidden + "\n" +
		"color: \"" + profile.Color + "\"\n" +
		"permission:\n" +
		"  edit: \"allow\"\n" +
		"  bash:\n" +
		"    \"*\": \"allow\"\n" +
		"  external_directory:\n" +
		"    \"*\": \"allow\"\n" +
		"---\n" +
		"\n" +
		"# " + profile.Name + " — " + profile.Area + "\n" +
		"\n" +
		"**Area:** " + profile.Area + "\n" +
		"**Expertise:** " + profile.Expertise + "\n" +
		"\n" +
		"---\n" +
		"\n" +
		"## What You Do\n" +
		"\n" +
		"You are a professional AI agent specialized in " + profile.Expertise + ".\n" +
		"You help with software engineering tasks in your domain.\n" +
		"You adapt to the user's project, preferences, and coding style over time.\n" +
		"\n" +
		"## Core Rules\n" +
		"\n" +
		"### Response Quality\n" +
		"- 50-150 words compact\n" +
		"- Icons + tables + visual hierarchy\n" +
		"- Result first, explanation after\n" +
		"\n" +
		"### Git Discipline\n" +
		"- No " + bc + "git add ." + bc + " — stage exact files\n" +
		"- No raw " + bc + "git push" + bc + " — use workflow commands\n" +
		"- No " + bc + "--force" + bc + ", " + bc + "--skip-gates" + bc + "\n" +
		"- Protected branches: main, master, develop, staging, prod, production\n" +
		"\n" +
		"### Security\n" +
		"- No " + bc + "sudo" + bc + " commands\n" +
		"- No " + bc + "pip install" + bc + " or " + bc + "npm install" + bc + " without approval\n" +
		"- No auth token exposure in output\n" +
		"\n" +
		"---\n" +
		"\n" +
		"*OVAV Product — Generated " + date + "*\n"
}

// generateMimocodeConfig creates mimocode.json for the product surface.
// Includes model routing, permissions, and minimal plugin config.
func generateMimocodeConfig(path string) error {
	content := "{" +
		"\n  \"$schema\": \"https://opencode.ai/config.json\"," +
		"\n  \"agent\": {}," +
		"\n  \"compaction\": {" +
		"\n    \"auto\": true," +
		"\n    \"preserve_recent_tokens\": 3000," +
		"\n    \"tail_turns\": 2" +
		"\n  }," +
		"\n  \"default_agent\": \"Platform Engineering\"," +
		"\n  \"instructions\": [" +
		"\n    \"OVAV_IDENTITY.md\"," +
		"\n    \"AGENTS.md\"" +
		"\n  ]," +
		"\n  \"mcp\": {}," +
		"\n  \"model\": \"openai/gpt-5.6-luna\"," +
		"\n  \"small_model\": \"minimax-coding-plan/MiniMax-M3\"," +
		"\n  \"permission\": {" +
		"\n    \"bash\": {" +
		"\n      \"*\": \"allow\"," +
		"\n      \"sudo *\": \"deny\"," +
		"\n      \"rm -rf / *\": \"deny\"," +
		"\n      \"git push --force *\": \"deny\"," +
		"\n      \"git push -f *\": \"deny\"," +
		"\n      \"npm install *\": \"ask\"," +
		"\n      \"pip install *\": \"ask\"" +
		"\n    }," +
		"\n    \"edit\": \"allow\"" +
		"\n  }," +
		"\n  \"plugin\": []," +
		"\n  \"model_routing\": {" +
		"\n    \"description\": \"Smart model distribution — auto-routes by task type\"," +
		"\n    \"default\": \"openai/gpt-5.6-luna\"," +
		"\n    \"fallback\": \"minimax-coding-plan/MiniMax-M3\"" +
		"\n  }," +
		"\n  \"provider\": {" +
		"\n    \"openai\": {" +
		"\n      \"options\": {" +
		"\n        \"timeout\": 300000" +
		"\n      }" +
		"\n    }" +
		"\n  }," +
		"\n  \"username\": \"\"" +
		"\n}\n"

	return os.WriteFile(path, []byte(content), 0644)
}
