#!/usr/bin/env bash
# OVAV Consumer Bootstrap — Template for new consumer projects
# v2.0.0 — OWS-HARDENING-v0.1.0: all 11 commands + SU flags
#
# Usage (run from consumer project root, AFTER bin/ovav-consumer register):
#   bin/ovav-consumer-bootstrap
#
# What this does:
#   1. Verifies the consumer is registered in OVAV's .ovav/registry/consumers.yaml
#   2. Installs OWS shell shim wrappers (all 11 commands) in consumer's bin/
#      WITH AUDIT TRAIL — every OWS invocation forwards logs to OVAV
#   3. Adds fish/bash aliases for the OWS commands
#   4. Creates .ovav/consumer-link.yaml pointing back to OVAV
#   5. NEVER mutates OVAV permission_authority.json (only CEO can)

set -euo pipefail

OVAV_ROOT="${OVAV_ROOT:-/home/braka/Systems/OVAV}"
CONSUMER_ROOT="$PWD"
OWS_BINDIR="$CONSUMER_ROOT/bin"

# ─── Detect consumer identity ───────────────────────────────────────────
if [ ! -f "$CONSUMER_ROOT/.ovav/config.yaml" ]; then
  echo "ERROR: .ovav/config.yaml not found. Are you in a consumer project root?" >&2
  echo "       (Or run bin/ovav-consumer register first to register.)" >&2
  exit 1
fi

CONSUMER_ID=$(grep -E "^project:" "$CONSUMER_ROOT/.ovav/config.yaml" | head -1 | sed 's/^project:[[:space:]]*//; s/"//g; s/'"'"'//g')
if [ -z "$CONSUMER_ID" ]; then
  echo "ERROR: Could not detect consumer ID from .ovav/config.yaml (project: line missing)" >&2
  exit 1
fi
echo "Consumer ID detected: $CONSUMER_ID"

# ─── Verify registration with OVAV ──────────────────────────────────────
REGISTRY="$OVAV_ROOT/.ovav/registry/consumers.yaml"
if [ ! -f "$REGISTRY" ]; then
  echo "ERROR: OVAV consumer registry not found at $REGISTRY" >&2
  echo "       Run 'bin/ovav-consumer register $CONSUMER_ID --root $CONSUMER_ROOT --waiver <file>' first" >&2
  exit 1
fi

# v2.0.0: check both id and aliases in registry
if ! grep -q "id: $CONSUMER_ID" "$REGISTRY" && ! grep -q "aliases:.*$CONSUMER_ID" "$REGISTRY"; then
  echo "ERROR: Consumer '$CONSUMER_ID' not registered in OVAV" >&2
  echo "       Run 'bin/ovav-consumer register $CONSUMER_ID --root $CONSUMER_ROOT --waiver <file>' first" >&2
  exit 1
fi

# Find the actual registered ID (may differ from config name due to aliases)
REGISTERED_ID=""
if grep -q "aliases:.*$CONSUMER_ID" "$REGISTRY"; then
  REGISTERED_ID=$(grep -B1 "aliases:.*$CONSUMER_ID" "$REGISTRY" | grep "id:" | head -1 | sed 's/.*id:[[:space:]]*//')
fi
if [ -z "$REGISTERED_ID" ]; then
  REGISTERED_ID=$(grep "id: $CONSUMER_ID" "$REGISTRY" | head -1 | sed 's/.*id:[[:space:]]*//')
fi
[ -z "$REGISTERED_ID" ] && REGISTERED_ID="$CONSUMER_ID"

STATE=$(grep -A 10 "id: $REGISTERED_ID" "$REGISTRY" | grep "state:" | head -1 | sed 's/.*state:[[:space:]]*//')
[ -z "$STATE" ] && STATE="unknown"
if [ "$STATE" = "revoked" ]; then
  echo "ERROR: Consumer '$CONSUMER_ID' is REVOKED. Cannot bootstrap." >&2
  exit 1
fi

echo "OK Consumer '$CONSUMER_ID' registered in OVAV (state: $STATE)"

# ─── Install OWS shim wrappers ──────────────────────────────────────────
mkdir -p "$OWS_BINDIR"

# Each OWS shim is a tiny wrapper that:
#   1. Forwards the call to OVAV's `go run` binary
#   2. Sets OVAV_CONSUMER_ID for audit
#   3. Limits scope to the consumer's project root

install_shim() {
  local cmd="$1"
  local shim_path="$OWS_BINDIR/$cmd"
  cat > "$shim_path" << SHIM
#!/usr/bin/env bash
# OVAV Consumer OWS shim — installed by ovav-consumer-bootstrap
# Forwards to OVAV binary with audit + consumer scope.
set -euo pipefail
export OVAV_ROOT="\${OVAV_ROOT:-/home/braka/Systems/OVAV}"
export OVAV_CONSUMER_ID="$CONSUMER_ID"
export OVAV_CONSUMER_ROOT="$CONSUMER_ROOT"
exec bash "\$OVAV_ROOT/bin/ovav-consumer-ows" "$cmd" "\$@"
SHIM
  if [ $? -ne 0 ]; then
    echo "  WARN: Failed to create shim $cmd" >&2
    return 1
  fi
  chmod +x "$shim_path"
  echo "  OK Shim installed: $shim_path"
}

echo ""
echo "Installing OWS shim wrappers in $OWS_BINDIR/"
# v2.0.0: all 11 OWS commands + SU-HARDENING flags
for cmd in owc owd owl owv ows owclean owm owx owa owr owlk; do
  install_shim "$cmd"
done

# ─── Create consumer-link.yaml (back-reference to OVAV) ────────────────
mkdir -p "$CONSUMER_ROOT/.ovav"
cat > "$CONSUMER_ROOT/.ovav/consumer-link.yaml" << LINK
# OVAV Consumer Link
# Generated by bin/ovav-consumer-bootstrap on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT EDIT BY HAND — re-run bootstrap to regenerate

consumer_id: $CONSUMER_ID
ovav_root: $OVAV_ROOT
state: $STATE
bootstrap_version: 1.0.0
bootstrap_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
shims_installed:
$(for cmd in owc owd owl owv ows owm owa owclean; do echo "  - $cmd"; done)
LINK

# ─── Add consumer bin/ to PATH (fish + bash) ───────────────────────────
ALIAS_MARKER="# OVAV consumer shims (auto-added by ovav-consumer-bootstrap)"

# v2.0.0: use fish_add_path / PATH export instead of per-command aliases
# This makes ALL 11 commands available without prefix

if [ -f "$HOME/.config/fish/config.fish" ]; then
  if ! grep -q "$ALIAS_MARKER" "$HOME/.config/fish/config.fish"; then
    cat >> "$HOME/.config/fish/config.fish" << FISH

$ALIAS_MARKER
fish_add_path "$OWS_BINDIR"
FISH
    echo "OK Fish PATH updated"
  fi
fi

if [ -f "$HOME/.bashrc" ]; then
  if ! grep -q "$ALIAS_MARKER" "$HOME/.bashrc"; then
    cat >> "$HOME/.bashrc" << BASHRC

$ALIAS_MARKER
export PATH="$OWS_BINDIR:\$PATH"
BASHRC
    echo "OK Bash PATH updated"
  fi
fi

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Consumer Bootstrap Complete: $CONSUMER_ID"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. CEO must run 'bin/ovav-consumer grant $CONSUMER_ID' to generate grant patch"
echo "  2. CEO reviews + applies patch to permission_authority.json"
echo "  3. CEO commits the patch"
echo "  4. Consumer can now invoke owc, owd, owl, etc. (each goes through OVAV audit)"
echo ""
echo "For details: cat $CONSUMER_ROOT/.ovav/consumer-link.yaml"
