/**
 * OVAV Monitor Plugin — Generated by tools/visual/monitor_engine.py
 * DO NOT EDIT DIRECTLY. Source: .ovav/visual/monitoring/monitoring.yaml
 *
 * Hooks into OpenCode events to provide real-time visual feedback:
 *   - Agent identity (Thavren ✦ / Eidren ✦)
 *   - Model tracking & switch alerts
 *   - Token usage & budget monitoring
 *   - OVAV memory capsule status
 *   - Session duration
 */

export const OVAVMonitor = async ({ client, $, project, directory }) => {
  // ── State ──────────────────────────────────────────────────────────────
  const state = {
    currentAgent: null,        // active_agent
    currentModel: null,        // current_model
    totalTokens: 0,            // token_usage
    budgetPercent: 0,          // budget
    budgetRemaining: "0",      // budget
    ovavMemoryActive: false,   // ovav_memory
    sessionActive: false,      // session
    sessionStart: null,        // session
    idleSince: null,           // session
  };

  // ── Helpers ────────────────────────────────────────────────────────────
  const toast = (message, duration = 3000) => {
    try {
      client.tui.toast.show({ message, duration });
    } catch (e) {
      console.log("[OVAV] toast failed:", e.message);
    }
  };

  const checkBudget = () => {
    // Budget thresholds from OVAV monitoring rules
    const MONTHLY_BUDGET = 100; // Default percentage-based
    const percent = Math.min(100, Math.round((state.totalTokens / 1000000) * 100)) / 100;
    state.budgetPercent = Math.round(percent);

    if (percent > 90 && !state._warnedCritical) {
      state._warnedCritical = true;
      toast(`🔴 PRESUPUESTO CRÍTICO: ${state.budgetPercent}%`, 8000);
    } else if (percent > 75 && !state._warnedWarning) {
      state._warnedWarning = true;
      toast(`⚠️ Presupuesto al ${state.budgetPercent}%`, 5000);
    } else if (percent <= 75) {
      state._warnedWarning = false;
      state._warnedCritical = false;
    }
  };

  console.log("[OVAV] Monitor plugin initialized");

  return {
    // ── Event Hooks ──────────────────────────────────────────────────────
    event: async ({ event }) => {
      switch (event.type) {
        case "session.status": {
          const status = event.properties;
          if (!status) break;

          // Track current agent
          if (status.agent && status.agent !== state.currentAgent) {
            const prev = state.currentAgent;
            state.currentAgent = status.agent;
            if (prev) {
              toast(`🔄 ${prev} → ${state.currentAgent}`, 3000);
            }
          }

          // Track current model
          if (status.model && status.model !== state.currentModel) {
            const prev = state.currentModel;
            state.currentModel = status.model;
            if (prev) {
              toast(`🧠 Modelo cambiado: ${prev} → ${state.currentModel}`, 3000);
            }
          }

          // Track token usage
          if (status.usage) {
            state.totalTokens = status.usage.total || status.usage.input + status.usage.output || 0;
            checkBudget();
          }
          break;
        }

        case "session.idle": {
          state.sessionActive = false;
          state.idleSince = Date.now();
          break;
        }

        case "session.created": {
          state.sessionActive = true;
          state.sessionStart = Date.now();
          state.idleSince = null;
          break;
        }

        case "todo.updated": {
          // Track plan changes for OVAV awareness
          break;
        }
      }
    },

    // ── Custom Tools ─────────────────────────────────────────────────────
    tool: {
      ovav_status: {
        description: "Get OVAV system status — agent, model, tokens, budget, memory",
        execute: async () => {
          const elapsed = state.sessionStart
            ? Math.floor((Date.now() - state.sessionStart) / 1000)
            : 0;
          const minutes = Math.floor(elapsed / 60);
          const seconds = elapsed % 60;

          return JSON.stringify({
            agent: state.currentAgent || "unknown",
            model: state.currentModel || "unknown",
            tokens: state.totalTokens,
            budgetPercent: state.budgetPercent,
            budgetRemaining: state.budgetRemaining,
            memoryActive: state.ovavMemoryActive,
            sessionElapsed: `${minutes}m ${seconds}s`,
            sessionActive: state.sessionActive,
          }, null, 2);
        },
      },
    },
  };
};
