name = "WSL · .config"
color = "cyan"
title = "WSL · {{cfg_dir}}"

[params.cfg_dir]
type = "text"
description = ".config working directory"
default = "/home/braka/.config"

[[panes]]
id = "config_main"
type = "terminal"
directory = "{{cfg_dir}}"
is_focused = true
commands = []
