package validators

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// HandoffSync validates that git-tracked state files exist and are consistent
// with git HEAD as the immutable source of truth. No auto-sync engines.
// Replaces: check_handoff_sync.py
type HandoffSync struct{}

func NewHandoffSync() *HandoffSync { return &HandoffSync{} }

func (h *HandoffSync) ID() string   { return "handoff_sync" }
func (h *HandoffSync) Name() string { return "Handoff Synchronization" }
func (h *HandoffSync) Description() string {
	return "Validates git-tracked state files: caps.yaml, CURRENT_HANDOFF.md"
}
func (h *HandoffSync) Weight() int { return 10 }

func (h *HandoffSync) Validate(ctx context.Context, root string) Result {
	start := time.Now()
	var issues []string

	// 1. Authority contract (caps.yaml) must exist
	capsPath := filepath.Join(root, ".ovav", "plan", "caps.yaml")
	if _, err := os.Stat(capsPath); os.IsNotExist(err) {
		issues = append(issues, "MISSING: .ovav/plan/caps.yaml — canonical authority source")
	} else if data, err := os.ReadFile(capsPath); err == nil {
		content := string(data)
		if !strings.Contains(content, "canonical") && !strings.Contains(content, "fuente de datos") {
			issues = append(issues, "AUTHORITY: caps.yaml should declare itself as canonical data source")
		}
	}

	// 2. CURRENT_HANDOFF.md exists (derived from git state)
	handoffPath := filepath.Join(root, ".ovav", "context", "CURRENT_HANDOFF.md")
	if _, err := os.Stat(handoffPath); os.IsNotExist(err) {
		issues = append(issues, "MISSING: CURRENT_HANDOFF.md — will be regenerated by session greeting")
	} else if data, err := os.ReadFile(handoffPath); err == nil {
		content := string(data)
		// Verify handoff is marked as generated
		if !strings.Contains(content, "GENERADO DESDE") && !strings.Contains(content, "SIN AUTORIDAD") {
			issues = append(issues, "HANDOFF: CURRENT_HANDOFF.md should be marked as generated (GENERADO DESDE / SIN AUTORIDAD)")
		}
	}

	// 3. No legacy sync engine files should exist
	deprecatedPaths := []string{
		"tools/agent_runtime/state_sync_engine.py",
	}
	for _, dp := range deprecatedPaths {
		if _, err := os.Stat(filepath.Join(root, dp)); err == nil {
			issues = append(issues, fmt.Sprintf("DEPRECATED: %s exists — git HEAD is the only source of truth", dp))
		}
	}

	if len(issues) > 0 {
		return Result{
			ID: h.ID(), Name: h.Name(), Status: "fail", Weight: h.Weight(),
			Message:  fmt.Sprintf("FAIL handoff sync — %d issue(s)", len(issues)),
			Issues:   issues,
			Duration: time.Since(start),
		}
	}
	return Result{
		ID: h.ID(), Name: h.Name(), Status: "pass", Weight: h.Weight(),
		Message:  "PASS handoff sync — git HEAD is the source of truth",
		Duration: time.Since(start),
	}
}

var _ Validator = (*HandoffSync)(nil)
