#!/bin/bash
# OVAV — Cloudflare Access Bypass for cPanel Health Endpoints
# =============================================================================
# DEG-003: cPanel health endpoints (/health, /api/v1/health) are intentionally
# public (ZERO auth middleware), but d678beea.ovav.dev sits behind Cloudflare Access
# Google OAuth. CI/CD health checks get 302 redirect → curl fails.
#
# This script DOCUMENTS the manual steps (not automated — requires CEO dashboard
# access). Run this as a reference, not as an executable.
# =============================================================================
# STATUS: Documentation-only. Requires CEO Cloudflare Dashboard access.
# =============================================================================

set -e

echo "============================================="
echo " Cloudflare Access Bypass — Setup Guide"
echo " DEG-003: cPanel /health bypass"
echo "============================================="
echo ""
echo "⚠️  ESTE SCRIPT ES SOLO DOCUMENTACIÓN."
echo "   Los pasos 1-3 requieren acceso al dashboard de Cloudflare."
echo "   No se pueden automatizar sin el token de CEO."
echo ""
echo "============================================="
echo " PASO 1: Crear Service Token en Cloudflare"
echo "============================================="
echo ""
echo "   1. Ir a: https://one.dash.cloudflare.com/"
echo "   2. Navegar a: Access → Service Auth → Create Service Token"
echo "      (o directamente: https://one.dash.cloudflare.com/<account>/access/service-tokens)"
echo "   3. Nombre: \"OVAV CI/CD Health Check\""
echo "   4. Duración: \"Never expires\" (o elige la que prefieras)"
echo "   5. Click \"Generate token\""
echo "   6. GUARDA los valores (solo se muestran una vez):"
echo "      - Client ID:    <copiar>"
echo "      - Client Secret: <copiar>"
echo ""
echo "============================================="
echo " PASO 2: Agregar Bypass Rule en Access"
echo "============================================="
echo ""
echo "   1. Ir a: https://one.dash.cloudflare.com/ → Access → Applications"
echo "   2. Seleccionar la aplicación: \"OVAV cPanel (d678beea.ovav.dev)\""
echo "   3. Ir a la pestaña: \"Policies\""
echo "   4. Click \"Add a policy\""
echo "   5. Nombre: \"Health Endpoint Bypass\""
echo "   6. Action: \"Bypass\"  ← IMPORTANTE: Bypass, no Allow"
echo "   7. Configure rule:"
echo ""
echo "      Selector:   Service Token"
echo "      Value:      \"OVAV CI/CD Health Check\" (el token creado en Paso 1)"
echo ""
echo "   8. Click \"Add a second include rule\" (AND condition):"
echo ""
echo "      Selector:   URI Path"
echo "      Operator:    matches regex"
echo "      Value:       ^/health$|^/api/v1/health$|^/health/?$|^/api/v1/health/?$"
echo ""
echo "      NOTA: La regla de URI Path asegura que este bypass SOLO aplique"
echo "            a los health endpoints, no a toda la aplicación."
echo ""
echo "   9. Click \"Save policy\""
echo ""
echo "   Diagrama de la policy:"
echo "   ┌─────────────────────────────────────────┐"
echo "   │ Policy: Health Endpoint Bypass          │"
echo "   │ Action: Bypass                          │"
echo "   │ Include: Service Token = OVAV CI/CD...  │"
echo "   │   AND   URI Path = ^/health$|^/api/... │"
echo "   │ No require rules                        │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "============================================="
echo " PASO 3: Agregar Secrets a GitHub"
echo "============================================="
echo ""
echo "   1. Ir a: https://github.com/ovav-systems/OVAV/settings/secrets/actions"
echo "   2. Agregar estos 2 secrets:"
echo ""
echo "      Name:  CF_ACCESS_CLIENT_ID"
echo "      Value: <Client ID del Paso 1>"
echo ""
echo "      Name:  CF_ACCESS_CLIENT_SECRET"
echo "      Value: <Client Secret del Paso 1>"
echo ""
echo "   3. El workflow deploy-cpanel.yml ya está preparado para usarlos."
echo "      Cuando los secrets existan, automáticamente usará las cabeceras:"
echo ""
echo "        CF-Access-Client-Id: \${{ secrets.CF_ACCESS_CLIENT_ID }}"
echo "        CF-Access-Client-Secret: \${{ secrets.CF_ACCESS_CLIENT_SECRET }}"
echo ""
echo "============================================="
echo " VERIFICACIÓN"
echo "============================================="
echo ""
echo "   Después de completar los 3 pasos, probar manualmente:"
echo ""
echo "   curl -H \"CF-Access-Client-Id: <client-id>\" \\"
echo "        -H \"CF-Access-Client-Secret: <client-secret>\" \\"
echo "        https://d678beea.ovav.dev/health"
echo ""
echo "   Debe devolver 200 + JSON con status: ok."
echo ""
echo "============================================="
echo " ESTADO ACTUAL (DEG-003)"
echo "============================================="
echo ""
echo "   Mientras NO exista el service token, deploy-cpanel.yml usa:"
echo "     ✅ Producción: https://ovav-systems.fly.dev/health     (raw Fly.io)"
echo "     ✅ Staging:    https://cpanel-staging.fly.dev/health   (raw Fly.io)"
echo ""
echo "   Ambos URLs evitan Cloudflare Access completamente."
echo "   Son funcionales pero no prueban el path edge → tunnel → backend."
echo ""
echo "   Una vez creado el service token, el workflow usará:"
echo "     ✅ Producción: https://d678beea.ovav.dev/health          (via CF Access)"
echo ""
echo "============================================="
echo " NOTAS ADICIONALES"
echo "============================================="
echo ""
echo "   - Los health endpoints NO tienen auth middleware por diseño."
echo "     Son públicos intencionalmente para health checks de Fly.io."
echo "   - Fly.io hace health checks via localhost:5858/health (interno)."
echo "   - Solo CI/CD externo necesita el bypass o raw Fly.io URL."
echo "   - El service token NUNCA debe commitearse al repo."
echo "   - El archivo .github/workflows/deploy-cpanel.yml ya referencia"
echo "     \${{ secrets.CF_ACCESS_CLIENT_ID }} y \${{ secrets.CF_ACCESS_CLIENT_SECRET }}"
echo "     en el paso de smoke test production."
echo ""
echo "============================================="
echo " REFERENCIAS"
echo "============================================="
echo ""
echo "   Cloudflare Docs:"
echo "   - Service tokens: https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/"
echo "   - Access policies: https://developers.cloudflare.com/cloudflare-one/policies/access/"
echo "   - Bypass action:  https://developers.cloudflare.com/cloudflare-one/policies/access/#bypass"
echo ""
echo "   Archivos relacionados en el repo:"
echo "   - .github/workflows/deploy-cpanel.yml   (health check URLs)"
echo "   - fly.toml                              (app: ovav-systems)"
echo "   - tools/infra/setup-access.sh           (Access app creation)"
echo "   - tools/infra/create-cf-access-bypass.sh (este archivo)"
echo ""
echo "Done. Revisa los pasos arriba ↑ y ejecútalos manualmente en el dashboard."
