#!/usr/bin/env python3
"""
OVAV Monitor Engine — Generates monitoring code from OVAV rules.

Lee .ovav/visual/monitoring/monitoring.yaml y genera:
  1. Plugin JS para OpenCode (toasts, tracking, alerts)
  2. Configuración de watchers para el dashboard OVAV

Usage:
    python3 tools/visual/monitor_engine.py --generate opencode  # Plugin JS
    python3 tools/visual/monitor_engine.py --validate           # Validar monitoring.yaml
    python3 tools/visual/monitor_engine.py --json               # Exportar como JSON

Location: tools/visual/monitor_engine.py
Depends on: .ovav/visual/monitoring/monitoring.yaml
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
MONITOR_PATH = ROOT / ".ovav" / "visual" / "monitoring" / "monitoring.yaml"


# ══════════════════════════════════════════════════════════════════════════════
# MONITOR LOADER
# ══════════════════════════════════════════════════════════════════════════════

class OVAVMonitor:
    """Carga y expone las reglas de monitoreo canónicas OVAV."""

    def __init__(self):
        if not MONITOR_PATH.exists():
            raise FileNotFoundError(f"Monitoring config not found: {MONITOR_PATH}")
        with open(MONITOR_PATH) as f:
            self._raw = yaml.safe_load(f)
        self._validate()

    def _validate(self):
        required = ["schema", "version", "watchers", "alerts", "projection"]
        missing = [k for k in required if k not in self._raw]
        if missing:
            raise ValueError(f"Monitoring missing keys: {missing}")

    def watchers(self) -> dict:
        return self._raw.get("watchers", {})

    def alerts(self) -> dict:
        return self._raw.get("alerts", {})

    def projection(self, client: str) -> dict:
        return self._raw.get("projection", {}).get(client, {})

    def raw(self) -> dict[str, Any]:
        return self._raw


# ══════════════════════════════════════════════════════════════════════════════
# OPENCODE PLUGIN JS GENERATOR
# ══════════════════════════════════════════════════════════════════════════════

def generate_opencode_plugin(monitor: OVAVMonitor) -> str:
    """Generate a complete OpenCode plugin JS from OVAV monitoring rules."""
    watchers = monitor.watchers()
    alerts = monitor.alerts()

    # Build alert handlers
    alert_handlers = _build_alert_handlers(alerts)

    # Build watcher state tracking
    state_vars = _build_state_variables(watchers)

    return f"""/**
 * OVAV Monitor Plugin — Generated by tools/visual/monitor_engine.py
 * DO NOT EDIT DIRECTLY. Source: .ovav/visual/monitoring/monitoring.yaml
 *
 * Hooks into OpenCode events to provide real-time visual feedback:
 *   - Agent identity (Thavren ✦ / Eidren ✦)
 *   - Model tracking & switch alerts
 *   - Token usage & budget monitoring
 *   - OVAV memory capsule status
 *   - Session duration
 */

export const OVAVMonitor = async ({{ client, $, project, directory }}) => {{
  // ── State ──────────────────────────────────────────────────────────────
{state_vars}

  // ── Helpers ────────────────────────────────────────────────────────────
  const toast = (message, duration = 3000) => {{
    try {{
      client.tui.toast.show({{ message, duration }});
    }} catch (e) {{
      console.log("[OVAV] toast failed:", e.message);
    }}
  }};

{_build_budget_helper()}

  // [OVAV] Monitor plugin initialized — silent (see .ovav/logs/monitor.log)

  return {{
    // ── Event Hooks ──────────────────────────────────────────────────────
    event: async ({{ event }}) => {{
      switch (event.type) {{
        case "session.status": {{
          const status = event.properties;
          if (!status) break;

          // Track current agent
          if (status.agent && status.agent !== state.currentAgent) {{
            const prev = state.currentAgent;
            state.currentAgent = status.agent;
            if (prev) {{
{_build_alert("agent_switch", alerts)}
            }}
          }}

          // Track current model
          if (status.model && status.model !== state.currentModel) {{
            const prev = state.currentModel;
            state.currentModel = status.model;
            if (prev) {{
{_build_alert("model_switch", alerts)}
            }}
          }}

          // Track token usage
          if (status.usage) {{
            state.totalTokens = status.usage.total || status.usage.input + status.usage.output || 0;
            checkBudget();
          }}
          break;
        }}

        case "session.idle": {{
          state.sessionActive = false;
          state.idleSince = Date.now();
          break;
        }}

        case "session.created": {{
          state.sessionActive = true;
          state.sessionStart = Date.now();
          state.idleSince = null;
          break;
        }}

        case "todo.updated": {{
          // Track plan changes for OVAV awareness
          break;
        }}
      }}
    }},

    // ── Custom Tools ─────────────────────────────────────────────────────
    tool: {{
      ovav_monitor: {{
        description: "Get OVAV monitor status — agent, model, tokens, budget, session uptime",
        execute: async () => {{
          const elapsed = state.sessionStart
            ? Math.floor((Date.now() - state.sessionStart) / 1000)
            : 0;
          const minutes = Math.floor(elapsed / 60);
          const seconds = elapsed % 60;

          return JSON.stringify({{
            agent: state.currentAgent || "unknown",
            model: state.currentModel || "unknown",
            tokens: state.totalTokens,
            budgetPercent: state.budgetPercent,
            budgetRemaining: state.budgetRemaining,
            memoryActive: state.ovavMemoryActive,
            sessionElapsed: `${{minutes}}m ${{seconds}}s`,
            sessionActive: state.sessionActive,
          }}, null, 2);
        }},
      }},
    }},
  }};
}};
"""


def _build_state_variables(watchers: dict) -> str:
    """Generate the state tracking variables."""
    lines = ["  const state = {"]
    lines.append('    currentAgent: null,        // active_agent')
    lines.append('    currentModel: null,        // current_model')
    lines.append('    totalTokens: 0,            // token_usage')
    lines.append('    budgetPercent: 0,          // budget')
    lines.append('    budgetRemaining: "0",      // budget')
    lines.append('    ovavMemoryActive: false,   // ovav_memory')
    lines.append('    sessionActive: false,      // session')
    lines.append('    sessionStart: null,        // session')
    lines.append('    idleSince: null,           // session')
    lines.append("  };")
    return "\n".join(lines)


def _build_alert_handlers(alerts: dict) -> str:
    """Generate alert handler functions."""
    # We inline alerts in the event handler instead
    return ""


def _build_alert(alert_name: str, alerts: dict) -> str:
    """Build the alert dispatch code for a specific alert."""
    alert = alerts.get(alert_name, {})
    if not alert:
        return f"              // {alert_name}: no config"

    toast_msg = alert.get("toast", "")
    severity = alert.get("severity", "info")
    duration = alert.get("duration_ms", 3000)

    # Replace template variables
    toast_msg = toast_msg.replace("{from}", "${prev}")
    toast_msg = toast_msg.replace("{to}", "${state.currentAgent}" if "agent" in alert_name else "${state.currentModel}")

    return f"""              toast(`{toast_msg}`, {duration});"""


def _build_budget_helper() -> str:
    """Generate the budget checking helper function."""
    return """  const checkBudget = () => {
    // Budget thresholds from OVAV monitoring rules
    const MONTHLY_BUDGET = 100; // Default percentage-based
    const percent = Math.min(100, Math.round((state.totalTokens / 1000000) * 100)) / 100;
    state.budgetPercent = Math.round(percent);

    if (percent > 90 && !state._warnedCritical) {
      state._warnedCritical = true;
      toast(`🔴 PRESUPUESTO CRÍTICO: ${state.budgetPercent}%`, 8000);
    } else if (percent > 75 && !state._warnedWarning) {
      state._warnedWarning = true;
      toast(`⚠️ Presupuesto al ${state.budgetPercent}%`, 5000);
    } else if (percent <= 75) {
      state._warnedWarning = false;
      state._warnedCritical = false;
    }
  };"""


# ══════════════════════════════════════════════════════════════════════════════
# VALIDATION
# ══════════════════════════════════════════════════════════════════════════════

def validate_monitoring(monitor: OVAVMonitor) -> dict[str, Any]:
    """Validate monitoring.yaml for completeness and correctness."""
    report = {"valid": True, "issues": [], "stats": {}}

    watchers = monitor.watchers()
    alerts = monitor.alerts()
    projection = monitor._raw.get("projection", {})

    report["stats"]["watchers"] = len(watchers)
    report["stats"]["alerts"] = len(alerts)
    report["stats"]["projections"] = len(projection)

    # Check required watchers
    required_watchers = ["active_agent", "current_model", "token_usage", "budget"]
    for w in required_watchers:
        if w not in watchers:
            report["issues"].append(f"Missing required watcher: {w}")
            report["valid"] = False

    # Check watchers have display formats
    for name, watcher in watchers.items():
        if "display" not in watcher:
            report["issues"].append(f"Watcher '{name}' missing display config")

    # Check alerts have triggers
    for name, alert in alerts.items():
        if "trigger" not in alert:
            report["issues"].append(f"Alert '{name}' missing trigger")

    return report


# ══════════════════════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════════════════════

def main():
    import argparse

    parser = argparse.ArgumentParser(description="OVAV Monitor Engine")
    parser.add_argument("--validate", action="store_true", help="Validar monitoring.yaml")
    parser.add_argument("--generate", choices=["opencode"], help="Generar código para cliente")
    parser.add_argument("--output", type=Path, help="Archivo de salida")
    parser.add_argument("--json", action="store_true", help="Exportar como JSON")

    args = parser.parse_args()

    try:
        monitor = OVAVMonitor()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    if args.validate:
        report = validate_monitoring(monitor)
        print(f"{'✅' if report['valid'] else '❌'} Monitoring valid: {report['stats']}")
        for issue in report["issues"]:
            print(f"  ⚠️  {issue}")
        return

    if args.generate == "opencode":
        plugin_js = generate_opencode_plugin(monitor)
        if args.output:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(plugin_js)
            print(f"✅ OpenCode plugin written to: {args.output}")
        else:
            print(plugin_js)

    elif args.json:
        print(json.dumps(monitor.raw(), indent=2))


if __name__ == "__main__":
    main()
